apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: udagram-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: udagram-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: udagram-front-end-svc
              servicePort: 80
