apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-api
spec:
  selector:
    matchLabels:
      app: udagram-user-api
  template:
    metadata:
      labels:
        app: udagram-user-api
    spec:
      containers:
      - name: udagram-user-api
        image: sukhrajklair/udagram-user-api:latest
        resources:
          requests:
              memory: "128Mi"
              cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
                secretKeyRef:
                  name: database-config
                  key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: database-config
                  key: POSTGRES_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
                secretKeyRef:
                  name: database-config
                  key: POSTGRES_DATABASE
          - name: POSTGRES_HOST
            valueFrom:
                secretKeyRef:
                  name: database-config
                  key: POSTGRES_HOST
          - name: AWS_REGION
            valueFrom:
                secretKeyRef:
                  name: aws-config
                  key: AWS_REGION    
          - name: AWS_PROFILE
            valueFrom:
                secretKeyRef:
                  name: aws-config
                  key: AWS_PROFILE
          - name: AWS_MEDIA_BUCKET
            valueFrom:
                secretKeyRef:
                  name: aws-config
                  key: AWS_MEDIA_BUCKET
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
          - name: URL
            valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: URL       
        ports:
        - containerPort: 8080
