version: "3.8"
services:
    udagram-user-api:
        build: 
            context: .
            dockerfile: .docker/userApi.dockerfile 
        image: sukhrajklair/udagram-user-api:latest

    udagram-feed-api:
        build: 
            context: .
            dockerfile: .docker/feedApi.dockerfile 
        image: sukhrajklair/udagram-feed-api:latest

    udagram-front-end:
        build:
            context: .
            dockerfile: .docker/frontEnd.dockerfile 
        image: sukhrajklair/udagram-front-end:latest
